/**
 * API surface consistency checker for ninox.
 *
 * Verifies that the public barrel (`src/index.ts`) and the docs (`API.md`)
 * agree on the exported symbol names, so the documented surface never drifts
 * from what is actually shipped. Run via: `bun run scripts/check-api.ts`.
 *
 * This is intentionally a lightweight regex-based extractor (the barrel and the
 * API tables are generated by humans with a stable shape); it is NOT a full TS
 * parser. If the export syntax or the API.md table format changes, update the
 * two extraction functions below.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Extract every named symbol re-exported from the barrel `src/index.ts`. */
function barrelExports(): Set<string> {
  const src = readFileSync(join(root, 'src/index.ts'), 'utf8');
  const names = new Set<string>();

  // export { A, B, C } from '...'  and  export type { A, B } from '...'
  const reExport = /export\s+(?:type\s+)?\{\s*([\s\S]*?)\s*\}\s*from\s+['"][^'"]+['"]/g;
  for (const m of src.matchAll(reExport)) {
    const block = m[1] ?? '';
    // Ignore aliased re-exports (e.g. `X as Y`) — we only track the exported name.
    for (const raw of block.split(',')) {
      const name = raw.trim().split(/\s+/)[0];
      if (name) names.add(name);
    }
  }
  return names;
}

/**
 * Extract every symbol name mentioned in API.md.
 *
 * Export names are consistently backtick-quoted; cells may span several
 * physical lines and list several names (e.g. `` `DataLoader` / `DataLoaderOptions` ``)
 * or include signatures (e.g. `` `defineCollection(name, schema, {...})` ``).
 * We scan every line, take each quoted token, strip parentheses, and keep the
 * leading identifier (dropping any `.member` suffix so `s.object` collapses
 * to `s`).
 */
function apiDocExports(): Set<string> {
  const src = readFileSync(join(root, 'API.md'), 'utf8');
  const names = new Set<string>();

  for (const line of src.split('\n')) {
    for (const quoted of line.match(/`([^`]+)`/g) ?? []) {
      const token = quoted.replace(/^`|`$/g, '');
      const stripped = token.replace(/\([^)]*\)/g, ''); // drop fn args
      const ident = (stripped.match(/[A-Za-z_$][\w$]*/) ?? [''])[0];
      if (ident) names.add(ident);
    }
  }
  return names;
}

const barrel = barrelExports();
const docs = apiDocExports();

// STRICT (fails CI): every barrel export must be documented in API.md.
const inBarrelNotDocs = [...barrel].filter((n) => !docs.has(n)).sort();
if (inBarrelNotDocs.length > 0) {
  console.error(`❌ In barrel but missing from API.md (${inBarrelNotDocs.length}):`);
  console.error(`   ${inBarrelNotDocs.join(', ')}`);
  process.exitCode = 1;
}

// WARNING only: API.md table cells also list option keys / params (e.g.
// `cache`, `dedupe`, `session`) that are not exports — so this direction is
// informational, not a failure.
const inDocsNotBarrel = [...docs].filter((n) => !barrel.has(n)).sort();
if (inDocsNotBarrel.length > 0) {
  console.warn(
    `⚠️  API.md mentions non-exported names (likely option keys/params, ${inDocsNotBarrel.length}):`,
  );
  console.warn(`   ${inDocsNotBarrel.join(', ')}`);
}

console.log(`✅ API surface consistent: ${barrel.size} barrel exports documented in API.md.`);
